# Generated by Django 4.1 on 2023-01-17 19:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Your Email')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True)),
                ('job_position', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, default='Still in progress')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('git_link', models.URLField(blank=True, default='Not available')),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.BooleanField(default=True)),
                ('little_description', models.TextField(blank=True)),
                ('facts', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='resume')),
                ('linkedin_link', models.URLField(blank=True, default='Not available')),
                ('github_link', models.URLField(blank=True, default='Not available')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('name_slug', models.SlugField(blank=True)),
                ('git_url', models.URLField(blank=True, default='Available soon')),
                ('video_link', models.URLField(blank=True, default='Available soon')),
                ('date_done', models.DateField(auto_now_add=True)),
                ('detail', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='project')),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(blank=True, max_length=100)),
                ('fiver_url', models.URLField(blank=True, default='Not available')),
                ('upwork_url', models.URLField(blank=True, default='Not available')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['skills'], name='home_skills_skills_1f6880_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['services'], name='home_servic_service_4bad0f_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_categories', to='home.category'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='services',
            field=models.ManyToManyField(related_name='portfolio_services', to='home.services'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.ManyToManyField(related_name='portfolio_skills', to='home.skills'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name'], name='home_contac_name_10e56e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='home_catego_name_a646c2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='home_projec_name_be1796_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['job_position', 'website'], name='home_portfo_job_pos_574d98_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['phone_number', 'city'], name='home_portfo_phone_n_02fe3b_idx'),
        ),
    ]
