# Generated by Django 4.1 on 2023-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='git_link',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linkedin_link',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='website',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_link',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='fiver_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='upwork_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/'),
        ),
    ]
