# Generated by Django 4.1 on 2023-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='service_hour',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_clients',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_projects',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='value_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skills',
            name='value_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
