# Generated by Django 4.1 on 2023-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio_service_hour_portfolio_total_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='freelance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
