# Generated by Django 4.1 on 2023-01-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_portfolio_freelance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.AddField(
            model_name='project',
            name='big_img',
            field=models.ImageField(null=True, upload_to='project_big'),
        ),
        migrations.AddField(
            model_name='project',
            name='small_img',
            field=models.ImageField(null=True, upload_to='project_small'),
        ),
    ]
