# Generated by Django 4.1 on 2023-01-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_project_img_project_big_img_project_small_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='freelance_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='website_link_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='git_url_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='video_link_on',
            field=models.BooleanField(default=False),
        ),
    ]
